import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ENTRY = resolve(ROOT, "frontend/src/runtime.js");
const OUTPUT = resolve(ROOT, "src/sphinx_yaq/_static/sphinx_yaq/yaq.js");
const CHECK = process.argv.includes("--check");

const result = await build({
  entryPoints: [ENTRY],
  bundle: true,
  write: false,
  format: "iife",
  target: ["es2018"],
  charset: "utf8",
  legalComments: "none",
  sourcemap: false,
  logLevel: "silent",
  banner: {
    js: "// Generated by npm run build:js from frontend/src/runtime.js. Do not edit.",
  },
});

const generated = result.outputFiles[0].contents;
if (CHECK) {
  let current;
  try {
    current = await readFile(OUTPUT);
  } catch (error) {
    if (error.code === "ENOENT") {
      throw new Error("Packaged JavaScript bundle is missing; run npm run build:js.");
    }
    throw error;
  }
  if (!current.equals(generated)) {
    throw new Error("Packaged JavaScript bundle is stale; run npm run build:js.");
  }
  console.log("Packaged JavaScript bundle is current.");
} else {
  await writeFile(OUTPUT, generated);
  console.log("Built src/sphinx_yaq/_static/sphinx_yaq/yaq.js.");
}
