// Generated by npm run build:js from frontend/src/runtime.js. Do not edit.
(() => {
  // frontend/src/grading.js
  var MathVariableError = class extends Error {
    constructor(message) {
      super(message);
      this.name = "MathVariable";
    }
  };
  function floatEqual(a, b) {
    if (a === b) {
      return true;
    }
    const difference = Math.abs(a - b);
    if (difference < 1e-8) {
      return true;
    }
    return difference <= 1e-8 * Math.min(Math.abs(a), Math.abs(b));
  }
  function compareMathExpressions(first, second, variables, tries, random = Math.random) {
    for (let trial = 0; trial < tries; trial += 1) {
      const scope = {};
      for (const [key, value] of Object.entries(variables)) {
        scope[key] = random() * (value[1] - value[0]) + value[0];
      }
      const firstResult = first.evaluate(scope);
      const secondResult = second.evaluate(scope);
      if (typeof firstResult !== "number" || typeof secondResult !== "number") {
        throw new MathVariableError("Some variables wee not substituted");
      }
      if (!floatEqual(firstResult, secondResult)) {
        return false;
      }
    }
    return true;
  }
  function allTrim(value) {
    return value.replace(/\s+/g, " ").replace(/^\s+|\s+$/g, "");
  }
  function compareValue(correctAnswers, givenAnswer, options) {
    let candidate = givenAnswer;
    if (options.noSpace) {
      candidate = candidate.replace(/\s/g, "");
    }
    for (let index = 0; index < correctAnswers.length; index += 1) {
      let matches = false;
      let correct = correctAnswers[index];
      if (options.noSpace) {
        correct = correct.replace(/\s/g, "");
      }
      if (options.math) {
        let correctExpression;
        try {
          correctExpression = options.compileMath(correct);
        } catch (_error) {
          options.onCorrectAnswerSyntaxError(correct);
        }
        const givenExpression = options.compileMath(candidate);
        matches = compareMathExpressions(
          givenExpression,
          correctExpression,
          options.mathVariables,
          options.mathTries,
          options.random
        );
      } else if (options.fuzzy) {
        matches = options.fuzzyEqual(correct, candidate);
      } else if (options.regex) {
        matches = new RegExp(correct).test(candidate);
      } else {
        matches = correct == candidate || Number(correct) == Number(candidate);
      }
      if (matches) {
        correctAnswers.splice(index, 1);
        return true;
      }
    }
    return false;
  }
  function testAnswer(correctAnswer, givenAnswer, options = {}) {
    const settings = {
      sequence: false,
      fuzzy: false,
      noSpace: false,
      math: false,
      regex: false,
      ordered: false,
      mathVariables: {},
      mathTries: 50,
      random: Math.random,
      fuzzyEqual: (first, second) => first === second,
      compileMath: void 0,
      onCorrectAnswerSyntaxError: () => {
      },
      ...options
    };
    const correctAnswers = settings.sequence ? allTrim(correctAnswer).split(/[\s,;]+/) : [correctAnswer];
    const givenAnswers = settings.sequence ? allTrim(givenAnswer).split(/[\s,;]+/) : [givenAnswer];
    const expectedElements = correctAnswers.length;
    let correctElements = 0;
    let wrongElements = 0;
    for (let index = 0; index < givenAnswers.length; index += 1) {
      const candidates = settings.ordered ? [correctAnswers[index]] : correctAnswers;
      if (compareValue(candidates, givenAnswers[index], settings)) {
        correctElements += 1;
      } else {
        wrongElements += 1;
      }
    }
    return expectedElements === correctElements && wrongElements === 0;
  }

  // frontend/src/model.js
  var QuestionState = Object.freeze({
    unsolved: 1,
    correct: 2,
    wrong: 4,
    solved: 8
  });
  var ActivityState = Object.freeze({
    ongoing: 1,
    solvable: 2,
    ended: 4
  });
  function answerChanged(model) {
    return { ...model, state: QuestionState.unsolved };
  }
  function gradeAnswer(model, { answered, correct }) {
    if (!answered) {
      return { ...model, state: QuestionState.unsolved };
    }
    if (correct) {
      return { ...model, enabled: false, state: QuestionState.correct };
    }
    return { ...model, enabled: true, state: QuestionState.wrong };
  }
  function revealAnswer(model) {
    return { ...model, enabled: false, state: QuestionState.solved };
  }
  function resetAnswer(model) {
    return { ...model, enabled: true, state: QuestionState.unsolved };
  }
  function calculateActivityState(questionStates) {
    let allCorrect = true;
    let anyUnsolved = false;
    let allCorrectOrSolved = true;
    for (const state of questionStates) {
      if (state & QuestionState.unsolved) {
        anyUnsolved = true;
      }
      if (!(state & QuestionState.correct)) {
        allCorrect = false;
      }
      if (!(state & QuestionState.correct) && !(state & QuestionState.solved)) {
        allCorrectOrSolved = false;
      }
    }
    let activityState = allCorrectOrSolved ? ActivityState.ended : ActivityState.ongoing;
    if (!allCorrect && !anyUnsolved) {
      activityState |= ActivityState.solvable;
    }
    return activityState;
  }

  // frontend/src/storage.js
  var STORAGE_SCHEMA_VERSION = 1;
  var STORAGE_NAMESPACE = "sphinx-yaq";
  var DEFAULT_SAVE_DELAY = 250;
  function normalizeDocumentScope(pathname) {
    try {
      const normalized = new URL(pathname || "/", "https://sphinx-yaq.invalid").pathname.replace(/\/{2,}/g, "/");
      return normalized.length > 1 ? normalized.replace(/\/$/, "") : "/";
    } catch (_error) {
      return "/";
    }
  }
  function hashString(value) {
    let hash = 2166136261;
    for (let index = 0; index < value.length; index += 1) {
      hash ^= value.charCodeAt(index);
      hash = Math.imul(hash, 16777619);
    }
    return (hash >>> 0).toString(16).padStart(8, "0");
  }
  function fingerprintQuizDefinition(questionDefinitions) {
    return `fnv1a-${hashString(JSON.stringify(questionDefinitions))}`;
  }
  function storageKey(documentScope, quizId) {
    return [
      STORAGE_NAMESPACE,
      `v${STORAGE_SCHEMA_VERSION}`,
      encodeURIComponent(normalizeDocumentScope(documentScope)),
      encodeURIComponent(quizId)
    ].join(":");
  }
  function validPayload(payload, expectedFingerprint) {
    return Boolean(
      payload && payload.schemaVersion === STORAGE_SCHEMA_VERSION && payload.fingerprint === expectedFingerprint && payload.state && typeof payload.state === "object" && !Array.isArray(payload.state)
    );
  }
  var QuizStorage = class {
    constructor({
      globalObject = globalThis,
      documentScope = ((_a) => (_a = globalObject == null ? void 0 : globalObject.location) == null ? void 0 : _a.pathname)() || "/",
      saveDelay = DEFAULT_SAVE_DELAY,
      setTimer = ((_b) => (_b = globalObject == null ? void 0 : globalObject.setTimeout) == null ? void 0 : _b.bind(globalObject))() || setTimeout,
      clearTimer = ((_c) => (_c = globalObject == null ? void 0 : globalObject.clearTimeout) == null ? void 0 : _c.bind(globalObject))() || clearTimeout
    } = {}) {
      this.globalObject = globalObject;
      this.documentScope = normalizeDocumentScope(documentScope);
      this.saveDelay = saveDelay;
      this.setTimer = setTimer;
      this.clearTimer = clearTimer;
      this.pending = /* @__PURE__ */ new Map();
      this.lastAvailable = void 0;
    }
    key(quizId) {
      return storageKey(this.documentScope, quizId);
    }
    getStorage() {
      try {
        const storage = this.globalObject.localStorage;
        if (!storage) {
          this.lastAvailable = false;
          return null;
        }
        return storage;
      } catch (_error) {
        this.lastAvailable = false;
        return null;
      }
    }
    isAvailable() {
      const storage = this.getStorage();
      if (!storage) {
        return false;
      }
      const probe = `${STORAGE_NAMESPACE}:probe`;
      try {
        storage.setItem(probe, probe);
        storage.removeItem(probe);
        this.lastAvailable = true;
        return true;
      } catch (_error) {
        this.lastAvailable = false;
        return false;
      }
    }
    get available() {
      return this.isAvailable();
    }
    load(quizId, expectedFingerprint) {
      const storage = this.getStorage();
      if (!storage) {
        return null;
      }
      try {
        const serialized = storage.getItem(this.key(quizId));
        if (serialized === null) {
          this.lastAvailable = true;
          return null;
        }
        const payload = JSON.parse(serialized);
        if (!validPayload(payload, expectedFingerprint)) {
          return null;
        }
        this.lastAvailable = true;
        return payload.state;
      } catch (_error) {
        this.lastAvailable = false;
        return null;
      }
    }
    save(quizId, fingerprint, state) {
      let serialized;
      try {
        serialized = JSON.stringify({
          schemaVersion: STORAGE_SCHEMA_VERSION,
          fingerprint,
          state
        });
      } catch (_error) {
        return false;
      }
      const key = this.key(quizId);
      this.cancel(key);
      const timer = this.setTimer(() => {
        this.pending.delete(key);
        this.write(key, serialized);
      }, this.saveDelay);
      this.pending.set(key, { timer, serialized });
      return true;
    }
    write(key, serialized) {
      const storage = this.getStorage();
      if (!storage) {
        return false;
      }
      try {
        storage.setItem(key, serialized);
        this.lastAvailable = true;
        return true;
      } catch (_error) {
        this.lastAvailable = false;
        return false;
      }
    }
    flush(quizId) {
      const keys = quizId === void 0 ? [...this.pending.keys()] : [this.key(quizId)];
      let succeeded = true;
      for (const key of keys) {
        const entry = this.pending.get(key);
        if (!entry) {
          continue;
        }
        this.clearTimer(entry.timer);
        this.pending.delete(key);
        succeeded = this.write(key, entry.serialized) && succeeded;
      }
      return succeeded;
    }
    cancel(key) {
      const entry = this.pending.get(key);
      if (entry) {
        this.clearTimer(entry.timer);
        this.pending.delete(key);
      }
    }
    remove(quizId) {
      const key = this.key(quizId);
      this.cancel(key);
      const storage = this.getStorage();
      if (!storage) {
        return false;
      }
      try {
        storage.removeItem(key);
        this.lastAvailable = true;
        return true;
      } catch (_error) {
        this.lastAvailable = false;
        return false;
      }
    }
    clearAll() {
      for (const entry of this.pending.values()) {
        this.clearTimer(entry.timer);
      }
      this.pending.clear();
      const storage = this.getStorage();
      if (!storage) {
        return false;
      }
      try {
        const keys = [];
        for (let index = 0; index < storage.length; index += 1) {
          const key = storage.key(index);
          if (key == null ? void 0 : key.startsWith(`${STORAGE_NAMESPACE}:`)) {
            keys.push(key);
          }
        }
        keys.forEach((key) => storage.removeItem(key));
        this.lastAvailable = true;
        return true;
      } catch (_error) {
        this.lastAvailable = false;
        return false;
      }
    }
  };

  // frontend/src/runtime.js
  var yaq_app = (function() {
    var self = {};
    var quizz = [];
    var quizIdentifiers = /* @__PURE__ */ new Set();
    var texts = {
      "True": "V",
      "False": "F",
      "dontKnow": "?",
      "gradeButtonText": "Corriger",
      "resetButtonText": "Recommencer",
      "solveButtonText": "Montrer la solution",
      "wrongMathVariableError": "L'expression contient une variable inconnue, les variables connues sont : ",
      "wrongMathSyntaxError": "L'expression contient une erreur de syntaxe.",
      "wrongMathError": "Expression mathematique : erreur inconnue."
    };
    function getDefault(tryValue, defaultValue) {
      if (tryValue === void 0)
        return defaultValue;
      return tryValue;
    }
    function blink(elem) {
      elem.classList.remove("yaq-blink");
      void elem.offsetWidth;
      elem.classList.add("yaq-blink");
    }
    function createElement(tag, className, text) {
      const element = document.createElement(tag);
      if (className) element.className = className;
      if (text !== void 0) element.textContent = text;
      return element;
    }
    function createFeedbackMarker(className, role, symbol, label) {
      const marker = createElement("span", "yaq-marker yaq-hidden " + className);
      marker.dataset.role = role;
      marker.title = label;
      const icon = createElement("span", null, symbol);
      icon.setAttribute("aria-hidden", "true");
      marker.append(icon, createElement("span", "yaq-feedback-text", " " + label));
      return marker;
    }
    function questionContext(element, index) {
      var _a, _b;
      const surrounding = (_a = element.parentElement) == null ? void 0 : _a.cloneNode(true);
      surrounding == null ? void 0 : surrounding.querySelectorAll(".yaq-q, .yaq-spoiler-inline-hidden").forEach((node) => node.remove());
      const prose = ((_b = surrounding == null ? void 0 : surrounding.textContent) == null ? void 0 : _b.replace(/\s+/g, " ").trim()) || "";
      return "Question " + (index + 1) + (prose ? ": " + prose : "");
    }
    function setVisible(element, visible) {
      element.style.display = visible ? "" : "none";
    }
    var questionConstructors = {};
    function isQuestionState(value) {
      return value === QuestionState.unsolved || value === QuestionState.correct || value === QuestionState.wrong || value === QuestionState.solved;
    }
    var Switch3 = (function() {
      function getDefaultModelSwitch3(selectedIndex, enabled) {
        enabled = getDefault(enabled, true);
        selectedIndex = getDefault(selectedIndex, 1);
        return {
          "enabled": enabled,
          "selectedIndex": selectedIndex
        };
      }
      function Switch32(_model, onChange) {
        this.model = getDefaultModelSwitch3();
        this.__onChange = onChange || function() {
        };
        this.rootDomElement = void 0;
        this.__buttons = void 0;
        this.__values = [texts["True"], texts["dontKnow"], texts["False"]];
        this.__updateSelection = function() {
          this.__buttons.forEach((button, index) => {
            const selected = index === this.model.selectedIndex;
            button.classList.toggle("yaq-switch3-button-active", selected);
            button.classList.toggle("yaq-switch3-button-notActive", !selected);
            button.classList.toggle("yaq-switch3-button-disabled", selected && !this.model.enabled);
            button.setAttribute("aria-pressed", String(selected));
          });
        };
        this.__updateEnabled = function() {
          this.__buttons.forEach((button) => {
            button.disabled = !this.model.enabled;
            button.classList.toggle("yaq-interractiveElement", this.model.enabled);
          });
        };
        this.reset = function() {
          this.model.enabled = true;
          this.model.selectedIndex = 1;
          this.render();
        };
        this.setEnabled = function(enabled) {
          this.model.enabled = enabled;
          this.render();
        };
        this.setSelectedIndex = function(index) {
          this.model.selectedIndex = index;
          this.render();
        };
        this.render = function() {
          this.__updateEnabled();
          this.__updateSelection();
        };
        this.__initEvents = function() {
          this.__buttons.forEach((button) => button.addEventListener("click", (e) => {
            if (this.model.enabled) {
              var newIndex = Number(e.currentTarget.dataset.index);
              if (newIndex !== this.model.selectedIndex) {
                this.model.selectedIndex = newIndex;
                this.render();
                this.__onChange();
              }
            }
          }));
        };
        this.__initDomElement = function() {
          var root = createElement("div", "yaq-switch3");
          this.rootDomElement = root;
          var container = createElement("div", "yaq-switch3-buttons");
          for (var i = 0; i < 3; i++) {
            var button = createElement("button", "yaq-switch3-button", this.__values[i]);
            button.type = "button";
            button.dataset.index = String(i);
            container.append(button);
          }
          this.__buttons = Array.from(container.children);
          root.append(container);
          this.__updateSelection();
          this.__updateEnabled();
          this.__initEvents();
        };
        this.__initDomElement();
        this.getModel = function() {
          return this.model;
        };
        this.getRootElement = function() {
          return this.rootDomElement;
        };
      }
      Switch32.getDefaultModel = getDefaultModelSwitch3;
      return Switch32;
    })();
    var FBQuestion = (function() {
      function getDefaultModel(enabled, state, value) {
        enabled = getDefault(enabled, true);
        state = getDefault(state, QuestionState.unsolved);
        value = getDefault(value, "");
        return {
          "enabled": enabled,
          "state": state,
          "value": value
        };
      }
      function FBQuestion2(params, onChange) {
        this.model = getDefaultModel();
        this.__flags = getDefault(params["flags"], "");
        this.__answer = getDefault(params["answer"], "");
        this.__size = getDefault(params["size"], 0);
        this.__math_vars = getDefault(params["vars"], {});
        this.__displayedAnswer = getDefault(params["displayed-answer"], this.__answer);
        this.rootDomElement = void 0;
        this.__input = void 0;
        this.__math_tries = 50;
        this.__warningMarker = void 0;
        this.__onChange = onChange || function() {
        };
        this.__updateEnabled = function() {
          this.__input.disabled = !this.model.enabled;
        };
        this.__updateState = function() {
          this.__warningMarker.classList.add("yaq-hidden");
        };
        this.__updateValue = function() {
          if (this.__input.value !== this.model.value) {
            this.__input.value = this.model.value;
          }
        };
        this.render = function() {
          this.__updateEnabled();
          this.__updateValue();
        };
        this.__initDomElement = function() {
          var root = createElement("span", "yaq-FBQuestion");
          this.rootDomElement = root;
          var input = createElement("input");
          input.type = "text";
          this.__input = input;
          if (this.__size !== 0) {
            input.size = this.__size;
          } else if (!this.__answser) {
            var l = this.__answer.length;
            input.size = Math.max(30, l + Math.round(l * 0.2));
          }
          this.__flags.split(",").forEach(function(elem) {
            if (elem)
              input.setAttribute("data-" + elem.trim(), "");
          });
          input.addEventListener("input", () => {
            this.model.value = this.__input.value;
            this.model = answerChanged(this.model);
            this.__warningMarker.classList.add("yaq-hidden");
            this.render();
            this.__onChange();
          });
          root.append(input);
          this.__warningMarker = createElement("span", "yaq-hidden yaq-warning-marker", "⚠");
          this.__warningMarker.dataset.role = "warningMarker";
          this.__warningMarker.setAttribute("role", "alert");
          root.append(this.__warningMarker);
          this.__updateEnabled();
          this.__updateState();
        };
        this.reset = function() {
          this.model = resetAnswer({ ...this.model, value: "" });
          this.__warningMarker.classList.add("yaq-hidden");
          this.render();
          this.__onChange();
        };
        this.getModel = function() {
          return this.model;
        };
        this.getPersistenceState = function() {
          return { type: "FB", enabled: this.model.enabled, state: this.model.state, value: this.model.value };
        };
        this.restore = function(state) {
          if (!state || state.type !== "FB" || typeof state.enabled !== "boolean" || !isQuestionState(state.state) || typeof state.value !== "string") return false;
          this.model = { enabled: state.enabled, state: state.state, value: state.value };
          this.render();
          return true;
        };
        this.getRootElement = function() {
          return this.rootDomElement;
        };
        this.grade = function() {
          var q = this.__input;
          var gans = this.model.value;
          if (gans) {
            var mathEq = q.hasAttribute("data-math");
            var fuzzy = q.hasAttribute("data-fuzzy");
            var sequence = q.hasAttribute("data-sequence");
            var nospace = q.hasAttribute("data-nospace");
            var regex = q.hasAttribute("data-regex");
            var ordered = q.hasAttribute("data-ordered");
            var ans = this.__answer;
            try {
              if (testAnswer(ans, gans, {
                sequence,
                fuzzy,
                noSpace: nospace,
                math: mathEq,
                mathVariables: this.__math_vars,
                mathTries: this.__math_tries,
                regex,
                ordered,
                fuzzyEqual: quasiEqualString,
                compileMath: math.compile.bind(math),
                random: Math.random,
                onCorrectAnswerSyntaxError: function(correctAnswer) {
                  window.alert("Failed to parse correct answer, contact website creator: " + correctAnswer);
                }
              })) {
                this.model = gradeAnswer(this.model, { answered: true, correct: true });
              } else {
                this.model = gradeAnswer(this.model, { answered: true, correct: false });
              }
            } catch (e) {
              if (e instanceof MathVariableError) {
                this.__warningMarker.title = texts["wrongMathVariableError"] + Object.keys(this.__math_vars).join(", ");
              } else if (e instanceof SyntaxError) {
                this.__warningMarker.title = texts["wrongMathSyntaxError"] + " " + e.message;
              } else {
                this.__warningMarker.title = texts["wrongMathError"] + e.message;
              }
              this.__warningMarker.classList.remove("yaq-hidden");
              this.__warningMarker.textContent = "⚠ " + this.__warningMarker.title;
              blink(q);
            }
          } else {
            this.model = gradeAnswer(this.model, { answered: false, correct: false });
            blink(q);
          }
          this.render();
          this.__onChange();
        };
        this.solve = function() {
          this.model = revealAnswer({ ...this.model, value: this.__displayedAnswer });
          this.render();
          this.__onChange();
        };
        this.__initDomElement();
      }
      FBQuestion2.getDefaultModel = getDefaultModel;
      FBQuestion2.QuestionStateEnum = QuestionState;
      questionConstructors["FB"] = FBQuestion2;
      return FBQuestion2;
    })();
    var ListQuestion = (function() {
      function getDefaultModel(enabled, state, selectedValue) {
        enabled = getDefault(enabled, true);
        state = getDefault(state, QuestionState.unsolved);
        selectedValue = getDefault(selectedValue, "");
        return {
          "enabled": enabled,
          "state": state,
          "selectedValue": selectedValue
        };
      }
      function ListQuestion2(params, onChange) {
        this.model = getDefaultModel();
        this.__values = getDefault(params["values"], "");
        this.__answer = getDefault(params["answer"], "");
        this.rootDomElement = void 0;
        this.__input = void 0;
        this.__onChange = onChange || function() {
        };
        this.__updateEnabled = function() {
          this.__input.disabled = !this.model.enabled;
        };
        this.__updateState = function() {
        };
        this.__updateSelectedElement = function() {
          if (this.model.selectedValue !== this.__input.value) {
            this.__input.value = this.model.selectedValue;
          }
        };
        this.render = function() {
          this.__updateEnabled();
          this.__updateSelectedElement();
        };
        this.__initDomElement = function() {
          var root = createElement("span", "yaq-FBQuestion");
          this.rootDomElement = root;
          var input = createElement("select");
          this.__input = input;
          const emptyOption = createElement("option");
          emptyOption.value = "";
          input.append(emptyOption);
          this.__values.split(",").forEach(
            function(elem) {
              elem = elem.trim();
              const option = createElement("option", null, elem);
              option.value = elem;
              input.append(option);
            }
          );
          input.addEventListener("change", () => {
            this.model.selectedValue = this.__input.value;
            this.model = answerChanged(this.model);
            this.render();
            this.__onChange();
          });
          root.append(input);
          this.__updateEnabled();
          this.__updateState();
        };
        this.reset = function() {
          this.model = resetAnswer({ ...this.model, selectedValue: "" });
          this.render();
          this.__onChange();
        };
        this.getModel = function() {
          return this.model;
        };
        this.getPersistenceState = function() {
          return { type: "SC", enabled: this.model.enabled, state: this.model.state, selectedValue: this.model.selectedValue };
        };
        this.restore = function(state) {
          if (!state || state.type !== "SC" || typeof state.enabled !== "boolean" || !isQuestionState(state.state) || typeof state.selectedValue !== "string") return false;
          this.model = { enabled: state.enabled, state: state.state, selectedValue: state.selectedValue };
          this.render();
          return true;
        };
        this.getRootElement = function() {
          return this.rootDomElement;
        };
        this.grade = function() {
          var gans = this.model.selectedValue;
          if (gans.trim() === "") {
            this.model = gradeAnswer(this.model, { answered: false, correct: false });
            blink(this.__input);
          } else if (gans === this.__answer) {
            this.model = gradeAnswer(this.model, { answered: true, correct: true });
          } else {
            this.model = gradeAnswer(this.model, { answered: true, correct: false });
          }
          this.render();
          this.__onChange();
        };
        this.solve = function() {
          this.model = revealAnswer({ ...this.model, selectedValue: this.__answer });
          this.render();
          this.__onChange();
        };
        this.__initDomElement();
      }
      ListQuestion2.getDefaultModel = getDefaultModel;
      ListQuestion2.QuestionStateEnum = QuestionState;
      questionConstructors["SC"] = ListQuestion2;
      return ListQuestion2;
    })();
    var TFQuestion = (function() {
      var TrueIndexSwitch3 = 0;
      var FalseIndexSwitch3 = 2;
      function getDefaultModel(enabled, state, answer, explanation) {
        enabled = getDefault(enabled, true);
        state = getDefault(state, QuestionState.unsolved);
        return {
          "enabled": enabled,
          "state": state
        };
      }
      function TFQuestion2(params, onChange) {
        this.model = getDefaultModel();
        this.__answer = getDefault(params["answer"], "");
        this.rootDomElement = void 0;
        this.__switch3 = void 0;
        this.__onChange = onChange || function() {
        };
        this.__updateEnabled = function() {
          this.__switch3.setEnabled(this.model.enabled);
        };
        this.render = function() {
          this.__updateEnabled();
        };
        this.__updateState = function() {
        };
        this.__initDomElement = function() {
          var root = createElement("span", "yaq-TFQuestion");
          this.rootDomElement = root;
          this.__switch3 = new Switch3(void 0, (function() {
            this.model = answerChanged(this.model);
            this.__onChange();
          }).bind(this));
          this.model.innerModel = this.__switch3.model;
          root.append(this.__switch3.getRootElement());
          this.__updateEnabled();
          this.__updateState();
        };
        this.reset = function() {
          this.__switch3.reset();
          this.model = resetAnswer(this.model);
          this.render();
          this.__onChange();
        };
        this.getModel = function() {
          return this.model;
        };
        this.getPersistenceState = function() {
          return {
            type: "TF",
            enabled: this.model.enabled,
            state: this.model.state,
            selectedIndex: this.__switch3.getModel().selectedIndex
          };
        };
        this.restore = function(state) {
          if (!state || state.type !== "TF" || typeof state.enabled !== "boolean" || !isQuestionState(state.state) || ![0, 1, 2].includes(state.selectedIndex)) return false;
          this.model = { enabled: state.enabled, state: state.state };
          this.__switch3.setSelectedIndex(state.selectedIndex);
          this.render();
          return true;
        };
        this.getRootElement = function() {
          return this.rootDomElement;
        };
        this.grade = function() {
          var gans = this.__switch3.getModel().selectedIndex;
          var cans = this.__answer === "T" ? TrueIndexSwitch3 : FalseIndexSwitch3;
          if (gans === 1) {
            this.model = gradeAnswer(this.model, { answered: false, correct: false });
            blink(this.__switch3.rootDomElement);
          } else if (gans === cans) {
            this.model = gradeAnswer(this.model, { answered: true, correct: true });
          } else {
            this.model = gradeAnswer(this.model, { answered: true, correct: false });
          }
          this.render();
          this.__onChange();
        };
        this.solve = function() {
          var cans = this.__answer === "T" ? TrueIndexSwitch3 : FalseIndexSwitch3;
          this.__switch3.setSelectedIndex(cans);
          this.model = revealAnswer(this.model);
          this.render();
          this.__onChange();
        };
        this.__initDomElement();
      }
      TFQuestion2.getDefaultModel = getDefaultModel;
      TFQuestion2.QuestionStateEnum = QuestionState;
      questionConstructors["TF"] = TFQuestion2;
      return TFQuestion2;
    })();
    var QuestionContainer = (function() {
      function getDefaultModel(enabled, state) {
        enabled = getDefault(enabled, true);
        state = getDefault(state, QuestionState.unsolved);
        return {
          "enabled": enabled,
          "state": state
        };
      }
      function QuestionContainer2(innerQuestionParams, rootElement, onChange, context) {
        this.model = getDefaultModel();
        this.rootDomElement = rootElement;
        this.__innerQuestion = void 0;
        this.__wrongMarker = void 0;
        this.__correctMarker = void 0;
        this.__infoMarker = void 0;
        this.__unansweredMarker = void 0;
        this.__gradedUnanswered = false;
        this.__onChange = onChange || function() {
        };
        this.__updateEnabled = function() {
          this.__innerQuestion.getModel().enabled = this.model.enabled;
          this.__innerQuestion.render();
        };
        this.__updateState = function() {
          this.model.state = this.__innerQuestion.getModel().state;
          if (this.model.state == QuestionState.unsolved) {
            this.__wrongMarker.classList.add("yaq-hidden");
            this.__correctMarker.classList.add("yaq-hidden");
            this.__infoMarker.classList.add("yaq-hidden");
            this.__unansweredMarker.classList.toggle("yaq-hidden", !this.__gradedUnanswered);
          } else if (this.model.state & QuestionState.correct) {
            this.__unansweredMarker.classList.add("yaq-hidden");
            this.__wrongMarker.classList.add("yaq-hidden");
            this.__correctMarker.classList.remove("yaq-hidden");
            this.__infoMarker.classList.add("yaq-hidden");
          } else if (this.model.state & QuestionState.wrong) {
            this.__unansweredMarker.classList.add("yaq-hidden");
            this.__wrongMarker.classList.remove("yaq-hidden");
            this.__correctMarker.classList.add("yaq-hidden");
            this.__infoMarker.classList.add("yaq-hidden");
          } else if (this.model.state & QuestionState.solved) {
            this.__unansweredMarker.classList.add("yaq-hidden");
            this.__wrongMarker.classList.add("yaq-hidden");
            this.__correctMarker.classList.add("yaq-hidden");
            this.__infoMarker.classList.remove("yaq-hidden");
          }
        };
        this.__innerChanged = function() {
          this.__gradedUnanswered = false;
          this.model.innerModel = this.__innerQuestion.getModel();
          this.__updateState();
          this.__onChange();
        };
        this.__initDomElement = function(innerQuestionParams2) {
          var root;
          if (!this.rootDomElement) {
            root = createElement("span", "yaq-Question");
            this.rootDomElement = root;
          } else {
            root = this.rootDomElement;
            root.classList.remove("yaq-q");
            root.classList.add("yaq-Question");
          }
          var QuestionConstructor = questionConstructors[innerQuestionParams2.type];
          if (!QuestionConstructor)
            throw new Error("Unsupported YAQ question type: " + innerQuestionParams2.type);
          this.__innerQuestion = new QuestionConstructor(innerQuestionParams2, this.__innerChanged.bind(this));
          this.model.innerModel = this.__innerQuestion.getModel();
          root.append(this.__innerQuestion.getRootElement());
          const field = root.querySelector("input, select");
          if (field) field.setAttribute("aria-label", context);
          const switchGroup = root.querySelector(".yaq-switch3");
          if (switchGroup) {
            switchGroup.setAttribute("role", "group");
            switchGroup.setAttribute("aria-label", context);
            switchGroup.querySelectorAll("button").forEach((button, index) => {
              button.setAttribute("aria-label", ["True", "Unanswered", "False"][index]);
            });
          }
          this.__wrongMarker = createFeedbackMarker("yaq-wrong-marker", "wrongMarker", "✘", "Incorrect");
          this.__correctMarker = createFeedbackMarker("yaq-correct-marker", "correctMarker", "✔", "Correct");
          this.__infoMarker = createFeedbackMarker("yaq-solution-marker", "solutionMarker", "ⓘ", "Solution shown");
          this.__unansweredMarker = createFeedbackMarker("yaq-unanswered-marker", "unansweredMarker", "?", "Unanswered");
          root.append(this.__wrongMarker);
          root.append(this.__correctMarker);
          root.append(this.__infoMarker);
          root.append(this.__unansweredMarker);
          this.__updateEnabled();
          this.__updateState();
        };
        this.reset = function() {
          this.__gradedUnanswered = false;
          this.__innerQuestion.reset();
          this.model.enabled = true;
          this.__updateState();
        };
        this.getModel = function() {
          return this.model;
        };
        this.getPersistenceState = function() {
          return this.__innerQuestion.getPersistenceState();
        };
        this.restore = function(state) {
          if (!this.__innerQuestion.restore(state)) return false;
          this.model.innerModel = this.__innerQuestion.getModel();
          this.model.enabled = this.model.innerModel.enabled;
          this.__updateState();
          return true;
        };
        this.getRootElement = function() {
          return this.rootDomElement;
        };
        this.setEnabled = function(enabled) {
          this.model.enabled = enabled;
          this.__updateEnabled();
        };
        this.grade = function() {
          this.__innerQuestion.grade();
          this.__gradedUnanswered = this.__innerQuestion.getModel().state === QuestionState.unsolved;
          this.__updateState();
        };
        this.solve = function() {
          this.__innerQuestion.solve();
        };
        this.__initDomElement(innerQuestionParams);
      }
      QuestionContainer2.getDefaultModel = getDefaultModel;
      QuestionContainer2.QuestionStateEnum = QuestionState;
      return QuestionContainer2;
    })();
    var QuizActivity = (function() {
      function __b64DecodeUnicode(str) {
        return decodeURIComponent(atob(str).split("").map(function(c) {
          return "%" + ("00" + c.charCodeAt(0).toString(16)).slice(-2);
        }).join(""));
      }
      function getDefaultModel(enabled, state) {
        enabled = getDefault(enabled, true);
        state = getDefault(state, ActivityState.ongoing);
        return {
          "enabled": enabled,
          "state": state
        };
      }
      function QuizActivity2(sourceElement, onChange) {
        this.model = getDefaultModel();
        this.rootDomElement = void 0;
        this.__questions = [];
        this.__onChange = onChange || function() {
        };
        this.__updateEnabled = function() {
          this.__questions.forEach((function(elem) {
            elem.setEnabled(this.model.enabled);
          }).bind(this));
        };
        this.__updateState = function() {
          this.model.state = calculateActivityState(this.__questions.map(function(elem) {
            return elem.getModel().state;
          }));
        };
        this.__questionChanged = function() {
          this.__updateState();
          this.__onChange();
        };
        this.grade = function() {
          this.__questions.forEach(function(elem) {
            elem.grade();
          });
        };
        this.getNumberOfQuestions = function() {
          return this.__questions.length;
        };
        this.solve = function() {
          this.__questions.forEach(function(elem) {
            if (!(elem.getModel().state & QuestionState.solved) && elem.getModel().state & QuestionState.wrong) {
              elem.solve();
            }
          });
        };
        this.reset = function() {
          this.__questions.forEach(function(elem) {
            elem.reset();
          });
          this.model.enabled = true;
        };
        this.__initDomElement = function(sourceElement2) {
          var root = createElement("div", "yaq-activity");
          this.rootDomElement = root;
          root.append(...Array.from(sourceElement2.cloneNode(true).childNodes));
          const placeholders = Array.from(root.querySelectorAll(".yaq-q"));
          const contexts = placeholders.map((elem, index) => questionContext(elem, index));
          placeholders.forEach((elem, index) => {
            try {
              var textmodel = __b64DecodeUnicode(elem.getAttribute("data-model"));
              var model = JSON.parse(textmodel);
              var question = new QuestionContainer(model, elem, this.__questionChanged.bind(this), contexts[index]);
              this.__questions.push(question);
              this.model["innerModel" + index] = question.getModel();
            } catch (error) {
              console.error("YAQ: Error while initializing question.", error);
              elem.classList.remove("yaq-q", "yaq-Question");
              elem.classList.add("yaq-question-fallback");
              elem.append(createElement("span", null, " Interactive question unavailable."));
            }
          });
          this.__updateState();
          this.__updateEnabled();
        };
        this.__initDomElement(sourceElement);
        this.getModel = function() {
          return this.model;
        };
        this.getRootElement = function() {
          return this.rootDomElement;
        };
        this.getPersistenceState = function() {
          return {
            questions: this.__questions.map(function(question) {
              return question.getPersistenceState();
            })
          };
        };
        this.restore = function(state) {
          if (!state || !Array.isArray(state.questions) || state.questions.length !== this.__questions.length) return false;
          for (var index = 0; index < this.__questions.length; index++) {
            if (!this.__questions[index].restore(state.questions[index])) return false;
          }
          this.__updateState();
          return true;
        };
        this.setEnabled = function(enabled) {
          this.model.enabled = enabled;
          this.__updateEnabled();
        };
      }
      QuizActivity2.getDefaultModel = getDefaultModel;
      QuizActivity2.StateEnum = ActivityState;
      return QuizActivity2;
    })();
    var Quiz = (function() {
      function getDefaultModel(exerciceNumber, enabled, state, title) {
        enabled = getDefault(enabled, true);
        state = getDefault(state, ActivityState.ongoing);
        return {
          "enabled": enabled,
          "state": state
        };
      }
      function Quiz2(sourceElement, params, fingerprint) {
        this.model = getDefaultModel();
        this.__fingerprint = fingerprint;
        this.__exerciceNumber = getDefault(params["exerciceNumber"], 0);
        this.__title = getDefault(params["title"], "");
        this.__uid = params["uid"];
        if (!this.__uid)
          throw "Missing or invalid uid field in YAQ quiz model " + this.__uid;
        if (quizIdentifiers.has(this.__uid))
          throw "YAQ quiz uid is already used " + this.__uid;
        this.rootDomElement = void 0;
        this.__activity;
        this.__buttonGrade = void 0;
        this.__buttonReset = void 0;
        this.__buttonSolve = void 0;
        this.__status = void 0;
        this.__statusText = void 0;
        this.__announce = function(action) {
          const states = this.__activity.__questions.map((question) => question.getModel().state);
          const count = (state) => states.filter((value) => value === state).length;
          this.__statusText.textContent = action + ": " + count(QuestionState.correct) + " correct, " + count(QuestionState.wrong) + " incorrect, " + count(QuestionState.unsolved) + " unanswered, " + count(QuestionState.solved) + " solution shown.";
        };
        this.__updateEnabled = function() {
          [this.__buttonGrade, this.__buttonReset, this.__buttonSolve].forEach((button) => {
            button.disabled = !this.model.enabled;
            button.classList.toggle("yaq-interractiveElement", this.model.enabled);
          });
          this.__activity.setEnabled(this.model.enabled);
        };
        this.__updateState = function() {
          var flagEnd = Boolean(this.model.state & ActivityState.ended);
          setVisible(this.__buttonReset, flagEnd);
          setVisible(this.__buttonGrade, !flagEnd && Boolean(this.model.state & ActivityState.ongoing));
          setVisible(this.__buttonSolve, !flagEnd && Boolean(this.model.state & ActivityState.solvable));
        };
        this.__activityChanged = function() {
          this.model.innerModel = this.__activity.getModel();
          this.model.state = this.__activity.getModel().state;
          this.__updateState();
          this.__updateModel();
        };
        this.grade = function() {
          this.__activity.grade();
          this.__announce("Grading complete");
        };
        this.solve = function() {
          this.__activity.solve();
          this.__announce("Solutions shown");
        };
        this.reset = function() {
          this.__activity.reset();
          this.model.enabled = true;
          this.__updateEnabled();
          self.storage.remove(this.__uid);
          this.__announce("Quiz restarted");
        };
        this.__initEvent = function() {
          this.__buttonGrade.addEventListener("click", this.grade.bind(this));
          this.__buttonSolve.addEventListener("click", this.solve.bind(this));
          this.__buttonReset.addEventListener("click", this.reset.bind(this));
        };
        this.__updateModel = function() {
          self.storage.save(this.__uid, this.__fingerprint, this.getPersistenceState());
        };
        this.getPersistenceState = function() {
          return { activity: this.__activity.getPersistenceState() };
        };
        this.restore = function(state) {
          if (!state || !this.__activity.restore(state.activity)) return false;
          this.model.innerModel = this.__activity.getModel();
          this.model.state = this.model.innerModel.state;
          this.__updateState();
          return true;
        };
        this.__initDomElement = function(sourceElement2) {
          var root = createElement("div", "yaq-root");
          this.rootDomElement = root;
          const heading = createElement("h2", "yaq-head", "Exercice " + (this.__exerciceNumber + 1) + " : " + this.__title);
          root.append(heading);
          root.setAttribute("role", "region");
          root.setAttribute("aria-label", heading.textContent);
          var mainContent = createElement("div", "yaq-main-content");
          root.append(mainContent);
          this.__activity = new QuizActivity(sourceElement2, this.__activityChanged.bind(this));
          this.model.innerModel = this.__activity.getModel();
          mainContent.append(this.__activity.getRootElement());
          this.model.state = this.__activity.getModel().state;
          var footer = createElement("div", "yaq-footer");
          if (this.__activity.getNumberOfQuestions() === 0)
            footer.classList.add("yaq-hidden");
          this.__buttonGrade = createElement("button", "yaq-button", texts["gradeButtonText"]);
          this.__buttonGrade.type = "button";
          footer.append(this.__buttonGrade);
          this.__buttonSolve = createElement("button", "yaq-button", texts["solveButtonText"]);
          this.__buttonSolve.type = "button";
          footer.append(this.__buttonSolve);
          this.__buttonReset = createElement("button", "yaq-button", texts["resetButtonText"]);
          this.__buttonReset.type = "button";
          footer.append(this.__buttonReset);
          this.__status = createElement("div", "yaq-status");
          this.__status.setAttribute("role", "status");
          this.__status.setAttribute("aria-live", "polite");
          this.__statusText = createElement("span", "yaq-visually-hidden");
          this.__status.append(this.__statusText);
          footer.append(this.__status);
          root.append(footer);
          this.__updateEnabled();
          this.__updateState();
          this.__initEvent();
        };
        this.__initDomElement(sourceElement);
        this.getModel = (function() {
          return this.model;
        }).bind(this);
        this.getRootElement = (function() {
          return this.rootDomElement;
        }).bind(this);
      }
      Quiz2.getDefaultModel = getDefaultModel;
      Quiz2.StateEnum = ActivityState;
      return Quiz2;
    })();
    var Latinise = {};
    Latinise.latin_map = {
      "Á": "A",
      "Ă": "A",
      "Ắ": "A",
      "Ặ": "A",
      "Ằ": "A",
      "Ẳ": "A",
      "Ẵ": "A",
      "Ǎ": "A",
      "Â": "A",
      "Ấ": "A",
      "Ậ": "A",
      "Ầ": "A",
      "Ẩ": "A",
      "Ẫ": "A",
      "Ä": "A",
      "Ǟ": "A",
      "Ȧ": "A",
      "Ǡ": "A",
      "Ạ": "A",
      "Ȁ": "A",
      "À": "A",
      "Ả": "A",
      "Ȃ": "A",
      "Ā": "A",
      "Ą": "A",
      "Å": "A",
      "Ǻ": "A",
      "Ḁ": "A",
      "Ⱥ": "A",
      "Ã": "A",
      "Ꜳ": "AA",
      "Æ": "AE",
      "Ǽ": "AE",
      "Ǣ": "AE",
      "Ꜵ": "AO",
      "Ꜷ": "AU",
      "Ꜹ": "AV",
      "Ꜻ": "AV",
      "Ꜽ": "AY",
      "Ḃ": "B",
      "Ḅ": "B",
      "Ɓ": "B",
      "Ḇ": "B",
      "Ƀ": "B",
      "Ƃ": "B",
      "Ć": "C",
      "Č": "C",
      "Ç": "C",
      "Ḉ": "C",
      "Ĉ": "C",
      "Ċ": "C",
      "Ƈ": "C",
      "Ȼ": "C",
      "Ď": "D",
      "Ḑ": "D",
      "Ḓ": "D",
      "Ḋ": "D",
      "Ḍ": "D",
      "Ɗ": "D",
      "Ḏ": "D",
      "ǲ": "D",
      "ǅ": "D",
      "Đ": "D",
      "Ƌ": "D",
      "Ǳ": "DZ",
      "Ǆ": "DZ",
      "É": "E",
      "Ĕ": "E",
      "Ě": "E",
      "Ȩ": "E",
      "Ḝ": "E",
      "Ê": "E",
      "Ế": "E",
      "Ệ": "E",
      "Ề": "E",
      "Ể": "E",
      "Ễ": "E",
      "Ḙ": "E",
      "Ë": "E",
      "Ė": "E",
      "Ẹ": "E",
      "Ȅ": "E",
      "È": "E",
      "Ẻ": "E",
      "Ȇ": "E",
      "Ē": "E",
      "Ḗ": "E",
      "Ḕ": "E",
      "Ę": "E",
      "Ɇ": "E",
      "Ẽ": "E",
      "Ḛ": "E",
      "Ꝫ": "ET",
      "Ḟ": "F",
      "Ƒ": "F",
      "Ǵ": "G",
      "Ğ": "G",
      "Ǧ": "G",
      "Ģ": "G",
      "Ĝ": "G",
      "Ġ": "G",
      "Ɠ": "G",
      "Ḡ": "G",
      "Ǥ": "G",
      "Ḫ": "H",
      "Ȟ": "H",
      "Ḩ": "H",
      "Ĥ": "H",
      "Ⱨ": "H",
      "Ḧ": "H",
      "Ḣ": "H",
      "Ḥ": "H",
      "Ħ": "H",
      "Í": "I",
      "Ĭ": "I",
      "Ǐ": "I",
      "Î": "I",
      "Ï": "I",
      "Ḯ": "I",
      "İ": "I",
      "Ị": "I",
      "Ȉ": "I",
      "Ì": "I",
      "Ỉ": "I",
      "Ȋ": "I",
      "Ī": "I",
      "Į": "I",
      "Ɨ": "I",
      "Ĩ": "I",
      "Ḭ": "I",
      "Ꝺ": "D",
      "Ꝼ": "F",
      "Ᵹ": "G",
      "Ꞃ": "R",
      "Ꞅ": "S",
      "Ꞇ": "T",
      "Ꝭ": "IS",
      "Ĵ": "J",
      "Ɉ": "J",
      "Ḱ": "K",
      "Ǩ": "K",
      "Ķ": "K",
      "Ⱪ": "K",
      "Ꝃ": "K",
      "Ḳ": "K",
      "Ƙ": "K",
      "Ḵ": "K",
      "Ꝁ": "K",
      "Ꝅ": "K",
      "Ĺ": "L",
      "Ƚ": "L",
      "Ľ": "L",
      "Ļ": "L",
      "Ḽ": "L",
      "Ḷ": "L",
      "Ḹ": "L",
      "Ⱡ": "L",
      "Ꝉ": "L",
      "Ḻ": "L",
      "Ŀ": "L",
      "Ɫ": "L",
      "ǈ": "L",
      "Ł": "L",
      "Ǉ": "LJ",
      "Ḿ": "M",
      "Ṁ": "M",
      "Ṃ": "M",
      "Ɱ": "M",
      "Ń": "N",
      "Ň": "N",
      "Ņ": "N",
      "Ṋ": "N",
      "Ṅ": "N",
      "Ṇ": "N",
      "Ǹ": "N",
      "Ɲ": "N",
      "Ṉ": "N",
      "Ƞ": "N",
      "ǋ": "N",
      "Ñ": "N",
      "Ǌ": "NJ",
      "Ó": "O",
      "Ŏ": "O",
      "Ǒ": "O",
      "Ô": "O",
      "Ố": "O",
      "Ộ": "O",
      "Ồ": "O",
      "Ổ": "O",
      "Ỗ": "O",
      "Ö": "O",
      "Ȫ": "O",
      "Ȯ": "O",
      "Ȱ": "O",
      "Ọ": "O",
      "Ő": "O",
      "Ȍ": "O",
      "Ò": "O",
      "Ỏ": "O",
      "Ơ": "O",
      "Ớ": "O",
      "Ợ": "O",
      "Ờ": "O",
      "Ở": "O",
      "Ỡ": "O",
      "Ȏ": "O",
      "Ꝋ": "O",
      "Ꝍ": "O",
      "Ō": "O",
      "Ṓ": "O",
      "Ṑ": "O",
      "Ɵ": "O",
      "Ǫ": "O",
      "Ǭ": "O",
      "Ø": "O",
      "Ǿ": "O",
      "Õ": "O",
      "Ṍ": "O",
      "Ṏ": "O",
      "Ȭ": "O",
      "Ƣ": "OI",
      "Ꝏ": "OO",
      "Ɛ": "E",
      "Ɔ": "O",
      "Ȣ": "OU",
      "Ṕ": "P",
      "Ṗ": "P",
      "Ꝓ": "P",
      "Ƥ": "P",
      "Ꝕ": "P",
      "Ᵽ": "P",
      "Ꝑ": "P",
      "Ꝙ": "Q",
      "Ꝗ": "Q",
      "Ŕ": "R",
      "Ř": "R",
      "Ŗ": "R",
      "Ṙ": "R",
      "Ṛ": "R",
      "Ṝ": "R",
      "Ȑ": "R",
      "Ȓ": "R",
      "Ṟ": "R",
      "Ɍ": "R",
      "Ɽ": "R",
      "Ꜿ": "C",
      "Ǝ": "E",
      "Ś": "S",
      "Ṥ": "S",
      "Š": "S",
      "Ṧ": "S",
      "Ş": "S",
      "Ŝ": "S",
      "Ș": "S",
      "Ṡ": "S",
      "Ṣ": "S",
      "Ṩ": "S",
      "Ť": "T",
      "Ţ": "T",
      "Ṱ": "T",
      "Ț": "T",
      "Ⱦ": "T",
      "Ṫ": "T",
      "Ṭ": "T",
      "Ƭ": "T",
      "Ṯ": "T",
      "Ʈ": "T",
      "Ŧ": "T",
      "Ɐ": "A",
      "Ꞁ": "L",
      "Ɯ": "M",
      "Ʌ": "V",
      "Ꜩ": "TZ",
      "Ú": "U",
      "Ŭ": "U",
      "Ǔ": "U",
      "Û": "U",
      "Ṷ": "U",
      "Ü": "U",
      "Ǘ": "U",
      "Ǚ": "U",
      "Ǜ": "U",
      "Ǖ": "U",
      "Ṳ": "U",
      "Ụ": "U",
      "Ű": "U",
      "Ȕ": "U",
      "Ù": "U",
      "Ủ": "U",
      "Ư": "U",
      "Ứ": "U",
      "Ự": "U",
      "Ừ": "U",
      "Ử": "U",
      "Ữ": "U",
      "Ȗ": "U",
      "Ū": "U",
      "Ṻ": "U",
      "Ų": "U",
      "Ů": "U",
      "Ũ": "U",
      "Ṹ": "U",
      "Ṵ": "U",
      "Ꝟ": "V",
      "Ṿ": "V",
      "Ʋ": "V",
      "Ṽ": "V",
      "Ꝡ": "VY",
      "Ẃ": "W",
      "Ŵ": "W",
      "Ẅ": "W",
      "Ẇ": "W",
      "Ẉ": "W",
      "Ẁ": "W",
      "Ⱳ": "W",
      "Ẍ": "X",
      "Ẋ": "X",
      "Ý": "Y",
      "Ŷ": "Y",
      "Ÿ": "Y",
      "Ẏ": "Y",
      "Ỵ": "Y",
      "Ỳ": "Y",
      "Ƴ": "Y",
      "Ỷ": "Y",
      "Ỿ": "Y",
      "Ȳ": "Y",
      "Ɏ": "Y",
      "Ỹ": "Y",
      "Ź": "Z",
      "Ž": "Z",
      "Ẑ": "Z",
      "Ⱬ": "Z",
      "Ż": "Z",
      "Ẓ": "Z",
      "Ȥ": "Z",
      "Ẕ": "Z",
      "Ƶ": "Z",
      "Ĳ": "IJ",
      "Œ": "OE",
      "ᴀ": "A",
      "ᴁ": "AE",
      "ʙ": "B",
      "ᴃ": "B",
      "ᴄ": "C",
      "ᴅ": "D",
      "ᴇ": "E",
      "ꜰ": "F",
      "ɢ": "G",
      "ʛ": "G",
      "ʜ": "H",
      "ɪ": "I",
      "ʁ": "R",
      "ᴊ": "J",
      "ᴋ": "K",
      "ʟ": "L",
      "ᴌ": "L",
      "ᴍ": "M",
      "ɴ": "N",
      "ᴏ": "O",
      "ɶ": "OE",
      "ᴐ": "O",
      "ᴕ": "OU",
      "ᴘ": "P",
      "ʀ": "R",
      "ᴎ": "N",
      "ᴙ": "R",
      "ꜱ": "S",
      "ᴛ": "T",
      "ⱻ": "E",
      "ᴚ": "R",
      "ᴜ": "U",
      "ᴠ": "V",
      "ᴡ": "W",
      "ʏ": "Y",
      "ᴢ": "Z",
      "á": "a",
      "ă": "a",
      "ắ": "a",
      "ặ": "a",
      "ằ": "a",
      "ẳ": "a",
      "ẵ": "a",
      "ǎ": "a",
      "â": "a",
      "ấ": "a",
      "ậ": "a",
      "ầ": "a",
      "ẩ": "a",
      "ẫ": "a",
      "ä": "a",
      "ǟ": "a",
      "ȧ": "a",
      "ǡ": "a",
      "ạ": "a",
      "ȁ": "a",
      "à": "a",
      "ả": "a",
      "ȃ": "a",
      "ā": "a",
      "ą": "a",
      "ᶏ": "a",
      "ẚ": "a",
      "å": "a",
      "ǻ": "a",
      "ḁ": "a",
      "ⱥ": "a",
      "ã": "a",
      "ꜳ": "aa",
      "æ": "ae",
      "ǽ": "ae",
      "ǣ": "ae",
      "ꜵ": "ao",
      "ꜷ": "au",
      "ꜹ": "av",
      "ꜻ": "av",
      "ꜽ": "ay",
      "ḃ": "b",
      "ḅ": "b",
      "ɓ": "b",
      "ḇ": "b",
      "ᵬ": "b",
      "ᶀ": "b",
      "ƀ": "b",
      "ƃ": "b",
      "ɵ": "o",
      "ć": "c",
      "č": "c",
      "ç": "c",
      "ḉ": "c",
      "ĉ": "c",
      "ɕ": "c",
      "ċ": "c",
      "ƈ": "c",
      "ȼ": "c",
      "ď": "d",
      "ḑ": "d",
      "ḓ": "d",
      "ȡ": "d",
      "ḋ": "d",
      "ḍ": "d",
      "ɗ": "d",
      "ᶑ": "d",
      "ḏ": "d",
      "ᵭ": "d",
      "ᶁ": "d",
      "đ": "d",
      "ɖ": "d",
      "ƌ": "d",
      "ı": "i",
      "ȷ": "j",
      "ɟ": "j",
      "ʄ": "j",
      "ǳ": "dz",
      "ǆ": "dz",
      "é": "e",
      "ĕ": "e",
      "ě": "e",
      "ȩ": "e",
      "ḝ": "e",
      "ê": "e",
      "ế": "e",
      "ệ": "e",
      "ề": "e",
      "ể": "e",
      "ễ": "e",
      "ḙ": "e",
      "ë": "e",
      "ė": "e",
      "ẹ": "e",
      "ȅ": "e",
      "è": "e",
      "ẻ": "e",
      "ȇ": "e",
      "ē": "e",
      "ḗ": "e",
      "ḕ": "e",
      "ⱸ": "e",
      "ę": "e",
      "ᶒ": "e",
      "ɇ": "e",
      "ẽ": "e",
      "ḛ": "e",
      "ꝫ": "et",
      "ḟ": "f",
      "ƒ": "f",
      "ᵮ": "f",
      "ᶂ": "f",
      "ǵ": "g",
      "ğ": "g",
      "ǧ": "g",
      "ģ": "g",
      "ĝ": "g",
      "ġ": "g",
      "ɠ": "g",
      "ḡ": "g",
      "ᶃ": "g",
      "ǥ": "g",
      "ḫ": "h",
      "ȟ": "h",
      "ḩ": "h",
      "ĥ": "h",
      "ⱨ": "h",
      "ḧ": "h",
      "ḣ": "h",
      "ḥ": "h",
      "ɦ": "h",
      "ẖ": "h",
      "ħ": "h",
      "ƕ": "hv",
      "í": "i",
      "ĭ": "i",
      "ǐ": "i",
      "î": "i",
      "ï": "i",
      "ḯ": "i",
      "ị": "i",
      "ȉ": "i",
      "ì": "i",
      "ỉ": "i",
      "ȋ": "i",
      "ī": "i",
      "į": "i",
      "ᶖ": "i",
      "ɨ": "i",
      "ĩ": "i",
      "ḭ": "i",
      "ꝺ": "d",
      "ꝼ": "f",
      "ᵹ": "g",
      "ꞃ": "r",
      "ꞅ": "s",
      "ꞇ": "t",
      "ꝭ": "is",
      "ǰ": "j",
      "ĵ": "j",
      "ʝ": "j",
      "ɉ": "j",
      "ḱ": "k",
      "ǩ": "k",
      "ķ": "k",
      "ⱪ": "k",
      "ꝃ": "k",
      "ḳ": "k",
      "ƙ": "k",
      "ḵ": "k",
      "ᶄ": "k",
      "ꝁ": "k",
      "ꝅ": "k",
      "ĺ": "l",
      "ƚ": "l",
      "ɬ": "l",
      "ľ": "l",
      "ļ": "l",
      "ḽ": "l",
      "ȴ": "l",
      "ḷ": "l",
      "ḹ": "l",
      "ⱡ": "l",
      "ꝉ": "l",
      "ḻ": "l",
      "ŀ": "l",
      "ɫ": "l",
      "ᶅ": "l",
      "ɭ": "l",
      "ł": "l",
      "ǉ": "lj",
      "ſ": "s",
      "ẜ": "s",
      "ẛ": "s",
      "ẝ": "s",
      "ḿ": "m",
      "ṁ": "m",
      "ṃ": "m",
      "ɱ": "m",
      "ᵯ": "m",
      "ᶆ": "m",
      "ń": "n",
      "ň": "n",
      "ņ": "n",
      "ṋ": "n",
      "ȵ": "n",
      "ṅ": "n",
      "ṇ": "n",
      "ǹ": "n",
      "ɲ": "n",
      "ṉ": "n",
      "ƞ": "n",
      "ᵰ": "n",
      "ᶇ": "n",
      "ɳ": "n",
      "ñ": "n",
      "ǌ": "nj",
      "ó": "o",
      "ŏ": "o",
      "ǒ": "o",
      "ô": "o",
      "ố": "o",
      "ộ": "o",
      "ồ": "o",
      "ổ": "o",
      "ỗ": "o",
      "ö": "o",
      "ȫ": "o",
      "ȯ": "o",
      "ȱ": "o",
      "ọ": "o",
      "ő": "o",
      "ȍ": "o",
      "ò": "o",
      "ỏ": "o",
      "ơ": "o",
      "ớ": "o",
      "ợ": "o",
      "ờ": "o",
      "ở": "o",
      "ỡ": "o",
      "ȏ": "o",
      "ꝋ": "o",
      "ꝍ": "o",
      "ⱺ": "o",
      "ō": "o",
      "ṓ": "o",
      "ṑ": "o",
      "ǫ": "o",
      "ǭ": "o",
      "ø": "o",
      "ǿ": "o",
      "õ": "o",
      "ṍ": "o",
      "ṏ": "o",
      "ȭ": "o",
      "ƣ": "oi",
      "ꝏ": "oo",
      "ɛ": "e",
      "ᶓ": "e",
      "ɔ": "o",
      "ᶗ": "o",
      "ȣ": "ou",
      "ṕ": "p",
      "ṗ": "p",
      "ꝓ": "p",
      "ƥ": "p",
      "ᵱ": "p",
      "ᶈ": "p",
      "ꝕ": "p",
      "ᵽ": "p",
      "ꝑ": "p",
      "ꝙ": "q",
      "ʠ": "q",
      "ɋ": "q",
      "ꝗ": "q",
      "ŕ": "r",
      "ř": "r",
      "ŗ": "r",
      "ṙ": "r",
      "ṛ": "r",
      "ṝ": "r",
      "ȑ": "r",
      "ɾ": "r",
      "ᵳ": "r",
      "ȓ": "r",
      "ṟ": "r",
      "ɼ": "r",
      "ᵲ": "r",
      "ᶉ": "r",
      "ɍ": "r",
      "ɽ": "r",
      "ↄ": "c",
      "ꜿ": "c",
      "ɘ": "e",
      "ɿ": "r",
      "ś": "s",
      "ṥ": "s",
      "š": "s",
      "ṧ": "s",
      "ş": "s",
      "ŝ": "s",
      "ș": "s",
      "ṡ": "s",
      "ṣ": "s",
      "ṩ": "s",
      "ʂ": "s",
      "ᵴ": "s",
      "ᶊ": "s",
      "ȿ": "s",
      "ɡ": "g",
      "ᴑ": "o",
      "ᴓ": "o",
      "ᴝ": "u",
      "ť": "t",
      "ţ": "t",
      "ṱ": "t",
      "ț": "t",
      "ȶ": "t",
      "ẗ": "t",
      "ⱦ": "t",
      "ṫ": "t",
      "ṭ": "t",
      "ƭ": "t",
      "ṯ": "t",
      "ᵵ": "t",
      "ƫ": "t",
      "ʈ": "t",
      "ŧ": "t",
      "ᵺ": "th",
      "ɐ": "a",
      "ᴂ": "ae",
      "ǝ": "e",
      "ᵷ": "g",
      "ɥ": "h",
      "ʮ": "h",
      "ʯ": "h",
      "ᴉ": "i",
      "ʞ": "k",
      "ꞁ": "l",
      "ɯ": "m",
      "ɰ": "m",
      "ᴔ": "oe",
      "ɹ": "r",
      "ɻ": "r",
      "ɺ": "r",
      "ⱹ": "r",
      "ʇ": "t",
      "ʌ": "v",
      "ʍ": "w",
      "ʎ": "y",
      "ꜩ": "tz",
      "ú": "u",
      "ŭ": "u",
      "ǔ": "u",
      "û": "u",
      "ṷ": "u",
      "ü": "u",
      "ǘ": "u",
      "ǚ": "u",
      "ǜ": "u",
      "ǖ": "u",
      "ṳ": "u",
      "ụ": "u",
      "ű": "u",
      "ȕ": "u",
      "ù": "u",
      "ủ": "u",
      "ư": "u",
      "ứ": "u",
      "ự": "u",
      "ừ": "u",
      "ử": "u",
      "ữ": "u",
      "ȗ": "u",
      "ū": "u",
      "ṻ": "u",
      "ų": "u",
      "ᶙ": "u",
      "ů": "u",
      "ũ": "u",
      "ṹ": "u",
      "ṵ": "u",
      "ᵫ": "ue",
      "ꝸ": "um",
      "ⱴ": "v",
      "ꝟ": "v",
      "ṿ": "v",
      "ʋ": "v",
      "ᶌ": "v",
      "ⱱ": "v",
      "ṽ": "v",
      "ꝡ": "vy",
      "ẃ": "w",
      "ŵ": "w",
      "ẅ": "w",
      "ẇ": "w",
      "ẉ": "w",
      "ẁ": "w",
      "ⱳ": "w",
      "ẘ": "w",
      "ẍ": "x",
      "ẋ": "x",
      "ᶍ": "x",
      "ý": "y",
      "ŷ": "y",
      "ÿ": "y",
      "ẏ": "y",
      "ỵ": "y",
      "ỳ": "y",
      "ƴ": "y",
      "ỷ": "y",
      "ỿ": "y",
      "ȳ": "y",
      "ẙ": "y",
      "ɏ": "y",
      "ỹ": "y",
      "ź": "z",
      "ž": "z",
      "ẑ": "z",
      "ʑ": "z",
      "ⱬ": "z",
      "ż": "z",
      "ẓ": "z",
      "ȥ": "z",
      "ẕ": "z",
      "ᵶ": "z",
      "ᶎ": "z",
      "ʐ": "z",
      "ƶ": "z",
      "ɀ": "z",
      "ﬀ": "ff",
      "ﬃ": "ffi",
      "ﬄ": "ffl",
      "ﬁ": "fi",
      "ﬂ": "fl",
      "ĳ": "ij",
      "œ": "oe",
      "ﬆ": "st",
      "ₐ": "a",
      "ₑ": "e",
      "ᵢ": "i",
      "ⱼ": "j",
      "ₒ": "o",
      "ᵣ": "r",
      "ᵤ": "u",
      "ᵥ": "v",
      "ₓ": "x"
    };
    function latinise(s) {
      return s.replace(/[^A-Za-z0-9\[\] ]/g, function(a) {
        return Latinise.latin_map[a] || a;
      });
    }
    ;
    var latinize = latinise;
    function allTrim2(s) {
      return s.replace(/\s+/g, " ").replace(/^\s+|\s+$/, "");
    }
    ;
    function quasiEqualString(s1, s2, tolerance) {
      tolerance = tolerance || 0.8;
      function editDistance(s12, s22) {
        s12 = s12.toLowerCase();
        s22 = s22.toLowerCase();
        var costs = new Array();
        for (var i = 0; i <= s12.length; i++) {
          var lastValue = i;
          for (var j = 0; j <= s22.length; j++) {
            if (i == 0)
              costs[j] = j;
            else {
              if (j > 0) {
                var newValue = costs[j - 1];
                if (s12.charAt(i - 1) != s22.charAt(j - 1))
                  newValue = Math.min(
                    Math.min(newValue, lastValue),
                    costs[j]
                  ) + 1;
                costs[j - 1] = lastValue;
                lastValue = newValue;
              }
            }
          }
          if (i > 0)
            costs[s22.length] = lastValue;
        }
        return costs[s22.length];
      }
      function similarity(s12, s22) {
        var longer = s12;
        var shorter = s22;
        if (s12.length < s22.length) {
          longer = s22;
          shorter = s12;
        }
        var longerLength = longer.length;
        if (longerLength == 0) {
          return 1;
        }
        return (longerLength - editDistance(longer, shorter)) / parseFloat(longerLength);
      }
      s1 = latinise(allTrim2(s1));
      s2 = latinise(allTrim2(s2));
      return similarity(s1, s2) > 0.8;
    }
    function initFromObj(element, index, model) {
      model.exerciceNumber = index;
      var definitions = Array.from(element.querySelectorAll(".yaq-q"), (question) => question.getAttribute("data-model"));
      var fingerprint = fingerprintQuizDefinition(definitions);
      var quiz = new Quiz(element, model, fingerprint);
      var storedState = self.storage.load(quiz.__uid, fingerprint);
      if (storedState && !quiz.restore(storedState)) self.storage.remove(quiz.__uid);
      quizz.push(quiz);
      quizIdentifiers.add(quiz.__uid);
      element.replaceChildren(quiz.getRootElement());
    }
    var initialized = false;
    self.storage = void 0;
    self.clearStoredProgress = function() {
      return self.storage ? self.storage.clearAll() : false;
    };
    self.init = function() {
      if (initialized) {
        throw "Yaq init method cannot be called twice !";
      }
      initialized = true;
      self.storage = new QuizStorage({ globalObject: window });
      document.querySelectorAll(".yaq").forEach((element, index) => {
        var model = element.getAttribute("data-model");
        try {
          if (model) {
            model = JSON.parse(model);
            initFromObj(element, index, model);
          } else throw new Error("Empty model in YAQ quiz");
        } catch (error) {
          console.error("YAQ: Error while initializing quiz.", error);
          element.classList.add("yaq-quiz-fallback");
          element.append(createElement("p", null, "Interactive quiz unavailable."));
        }
        element.classList.add("yaq-active");
      });
      window.addEventListener("pagehide", () => {
        self.storage.flush();
      });
    };
    return self;
  })();
  globalThis.yaq_app = yaq_app;
  document.addEventListener("DOMContentLoaded", function() {
    yaq_app.init();
    document.querySelectorAll(".yaq-spoiler-inline-hidden").forEach((element) => {
      element.addEventListener("click", () => {
        element.classList.remove("yaq-spoiler-inline-hidden");
        element.removeAttribute("aria-label");
        element.disabled = true;
      });
    });
    for (var i = 0; i < 26; i++) {
      var letter = String.fromCharCode(97 + i);
      var letterCap = String.fromCharCode(65 + i);
      delete math.Unit.UNITS[letter];
      delete math.Unit.UNITS[letterCap];
    }
  });
})();
